"""
setup.py — Render.com deployment build script
──────────────────────────────────────────────
This file works in tandem with render.yaml.

HOW render.yaml USES THIS FILE
──────────────────────────────
render.yaml defines two steps:

    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: gunicorn src.app.app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120

Step 1 (requirements.txt) installs the runtime dependencies
  (CPU-only PyTorch, Flask, gunicorn, etc.)

Step 2 (pip install -e .) runs THIS file, which makes `src` a proper
  Python package so gunicorn can import `src.app.app:app` without any
  sys.path manipulation.

Without this file gunicorn raises:
    ModuleNotFoundError: No module named 'src'

PROJECT LAYOUT EXPECTED BY render.yaml
───────────────────────────────────────
brain-tumor-classifier/          ← Render clones here
├── setup.py                     ← this file  (project root)
├── render.yaml                  ← Render Blueprint
├── requirements.txt             ← runtime deps (Render build step 1)
├── src/
│   ├── __init__.py              ← makes src/ a package  (created below if missing)
│   └── app/
│       ├── __init__.py          ← makes src.app importable
│       ├── app.py               ← Flask application  (gunicorn entry point)
│       └── templates/
│           └── index.html
└── models/
    └── brain_tumor_efficientnetb0_final.pth   ← set MODEL_PATH env var to locate

USAGE
─────
Local development (editable — changes to src/ take effect immediately):
    pip install -e .

Render deployment (non-editable, triggered by buildCommand in render.yaml):
    pip install -r requirements.txt && pip install -e .

UPDATING render.yaml buildCommand
──────────────────────────────────
Change render.yaml from:
    buildCommand: pip install -r requirements.txt

To:
    buildCommand: pip install -r requirements.txt && pip install -e .
"""

from pathlib import Path
from setuptools import find_packages, setup

# ── Ensure src/__init__.py and src/app/__init__.py exist ─────────────────────
# Render clones a clean repo — these files must exist for find_packages() to
# discover src and src.app, and for gunicorn to import src.app.app:app.
HERE = Path(__file__).parent.resolve()
for pkg_init in [
    HERE / "src" / "__init__.py",
    HERE / "src" / "app" / "__init__.py",
]:
    pkg_init.parent.mkdir(parents=True, exist_ok=True)
    if not pkg_init.exists():
        pkg_init.write_text(
            "# Auto-generated by setup.py — required for gunicorn import resolution\n"
        )

# ── Read README for PyPI long description (optional, skipped if absent) ───────
long_desc = ""
readme = HERE / "README.md"
if readme.exists():
    long_desc = readme.read_text(encoding="utf-8")

# ── Package configuration ──────────────────────────────────────────────────────
setup(
    name="brain-tumor-classifier-app",
    version="1.0.0",
    description="Brain Tumor MRI Classifier — Flask inference server (Render deployment)",
    long_description=long_desc,
    long_description_content_type="text/markdown",
    python_requires=">=3.10",

    # Discover src/ and src/app/ from the project root.
    # This is what allows gunicorn to resolve: src.app.app:app
    packages=find_packages(
        where=".",
        exclude=[
            "notebooks",
            "notebooks.*",
            "tests",
            "tests.*",
        ],
    ),

    # Runtime dependencies mirror requirements.txt so `pip install -e .`
    # alone is sufficient in environments that don't use requirements.txt.
    # On Render, requirements.txt is installed first so these are no-ops.
    install_requires=[
        "torch>=2.1.0",
        "torchvision>=0.16.0",
        "efficientnet-pytorch>=0.7.1",
        "numpy>=1.24.0",
        "Pillow>=10.0.0",
        "opencv-python-headless>=4.8.0",
        "flask>=3.0.0",
        "flask-cors>=4.0.0",
        "gunicorn>=21.2.0",
    ],

    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
        ],
    },

    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Framework :: Flask",
    ],

    # Include HTML templates so they're accessible after install
    package_data={
        "src.app": ["templates/*.html"],
    },
)
